# 基础镜像
FROM nginx
# author
MAINTAINER kangfu

# 挂载目录
VOLUME /home/kangfu/projects/kangfu-ui
# 创建目录
RUN mkdir -p /home/kangfu/projects/kangfu-ui
# 指定路径
WORKDIR /home/kangfu/projects/kangfu-ui
# 复制conf文件到路径
COPY ./conf/nginx.conf /etc/nginx/nginx.conf
# 复制html文件到路径
COPY ./html/dist /home/kangfu/projects/kangfu-ui
